version: 2
jobs:
    build:
        working_directory: ~/PersonalWebsite
        docker:
            - image: circleci/node:7.10
        steps:
            - checkout
            - run: npm install
                   yarn remove hexo-renderer-ejs
                   yarn add hexo-renderer-jade
                   yarn add hexo-prism-plugin
                   hexo generate
            - deploy:
                    name: Production Deploy
                    command: |
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                          hexo generate
                          scp -r -o StrictHostKeyChecking=no /public $PROD_USER@$PROD_IP:/PersonalWebsite
                      fi
