version: 2
jobs:
        build:
                docker:
                        - image: circleci/node:7.10

                        working_directory: ~/PersonalWebsite

                        steps:
                                - checkout

                                - run: npm install

                                - run: yarn remove hexo-renderer-ejs

                                - run: yarn add hexo-renderer-jade

                                 -run: yarn add hexo-prism-plugin


                                 -run: hexo generate
